project:
  type: website
  preview: 
    port: 7000

metadata-files: 
  - _sidebar.yml
  
website:
  title: "Veera Vignesh"
  favicon: images/vv.png
  navbar:
    pinned: true
    right:
      - text: Home
        icon: house
        href: index.qmd
      - text: Blog
        icon: newspaper
        href: posts.qmd
      - text: Projects
        icon: database-check
        href: projects.qmd
      - text: Books
        icon: book
        href: books.qmd
      - text: "Notes"
        icon: pen
        href: notes.qmd
      - text: Resume
        icon: briefcase
        href: static/Veera_Vignesh_Senior_Data_Scientist.pdf
  page-footer:
    border: true
    left:
      <i class="bi bi-c-circle"></i> Veera Vignesh 2023
    center: 
      - icon: bookmark
        text: Resources
        href: resources/index.qmd
    right:
      - icon: code
        href: https://github.com/veeravignesh1/veeravignesh.dev/
      - icon: github
        href: https://github.com/veeravignesh1
      - icon: twitter
        href: https://twitter.com/veeravignesh1
  sidebar: 
    # Have used a temporary workaround for the expected behaviour of displaying sidebar in all pages
    # Have turned off sidebar in other pages that is not required
    - id: notes
      title: "Notes"
      style: floating
      collapse-level: 2
      align: left
      contents:
        - notes/dagshub.qmd
        - notes/dvc.qmd

  comments: 
    giscus: 
        repo: veeravignesh1/veeravignesh.dev
        theme: transparent_dark
        loading: lazy
        mapping: pathname
format:
  html:
    theme:
      dark: [zephyr,dark.scss]
      light: [zephyr,light.scss]
    # mainfont: Cambria, "Times New Roman", Times, serif
    fontsize: 1.1rem
    css: styles.css
    link-external-newwindow: true
    # link-external-filter: '^(?:http:|https:)\/\/veeravignesh\.dev\/'



